FROM openjdk:8-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk update && apk add --no-cache --virtual .tmp \
  tzdata; cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime; \
  echo "Asia/Shanghai" > /etc/timezone; \
  apk del .tmp

VOLUME /tmp
WORKDIR /opt
EXPOSE 80

COPY greenpay-admin/lib/ ./lib/
COPY greenpay-admin/target/app.jar ./app.jar
ENTRYPOINT ["java", "-Dspring.profiles.active=prod", "-jar", "/opt/app.jar"]
