server:
  port: 8097

logging:
  level:
    com.github.binarywang.wxpay: error
    me.chanjar.weixin: error
    com.esiran.greenpay.common.sign: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.158:3306/greenpay?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: ruixiao123
  redis:
    port: 6379
    host: 192.168.3.158
    password: ruixiao123
  resources:
    chain:
      strategy:
        content:
          enabled: true
