server:
  port: 8082

logging:
  level:
    com.github.binarywang.wxpay: fatal
    me.chanjar.weixin: fatal

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql/greenpay?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: greenpay
  redis:
    port: 6379
    host: redis
  resources:
    chain:
      strategy:
        content:
          enabled: true