server:
  port: 8081

logging:
  level:
    com.github.binarywang.wxpay: error
    me.chanjar.weixin: error

spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**

delay_queue:
  redis:
    default_key: 'greenpay:delay_queue'
  consumer:
    enabled: false

shiro:
  loginUrl: /login
  successUrl: /home